const COURSE_STATUS_TYPES = {
  DRAFT: 'DRAFT',
  RELEASED: 'RELEASED',
  ARCHIVED: 'ARCHIVED',
};

const COURSE_CONTENT_TYPES = {
  LECTURE_VIDEO: 'LECTURE_VIDEO',
  LECTURE_ARTICLE: 'LECTURE_ARTICLE',
  QUIZ: 'QUIZ',
  // CODING_EXERCISE: 'CODING_EXERCISE',
  // PRACTISE_TEST: 'PRACTISE_TEST',
  ASSIGNMENT: 'ASSIGNMENT',
};

const STUDENT_LEVELS = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  EXPERIENCED: 'EXPERIENCED',
  ALL: 'ALL',
};

const COURSE_CATEGORY = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  FULLSTACK: 'FULLSTACK',
  IOS: 'IOS',
  ANDROID: 'ANDROID',
  CLOUD: 'CLOUD',
};

module.exports = {
  COURSE_STATUS_TYPES,
  COURSE_CONTENT_TYPES,
  STUDENT_LEVELS,
  COURSE_CATEGORY,
};
